package entity;
// Generated 28 февр. 2024 г., 12:39:46 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.persistence.*;

import static jakarta.persistence.GenerationType.SEQUENCE;

/**
 * eProducts generated by hbm2java
 */
@Entity
@Table(name="products"
)
public class eProducts  implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy=SEQUENCE, generator="generator")
    @SequenceGenerator(name="generator",  sequenceName = "products_id_seq", allocationSize = 1)
    @Column(name="id", nullable=false)
     private int id;

    @Column(name="name")
     private String name;

    @Column(name="price", precision=20)
     private BigDecimal price;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="year_issue")
    @JsonFormat(pattern="yyy-MM-dd HH:mm:ss")
     private LocalDateTime year_issue;

    @Column(name="raiting")
     private double raiting;

    @Column(name="page_image")
     private String path_image = "def";

    @ManyToOne
    @JoinColumn(name="id_user", nullable=false)
    @JsonBackReference
    private eUsers user;

    public eProducts() {
    }

    public eProducts(String name, BigDecimal price, LocalDateTime year_issue, double raiting, String path_image) {
       this.name = name;
       this.price = price;
       this.year_issue = year_issue;
       this.raiting = raiting;
       this.path_image = path_image;
    }


    public eUsers getUser(){
        return this.user;
    }

    public void setUser(eUsers user){
        this.user = user;
    }

    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public LocalDateTime getYear_issue() {
        return this.year_issue;
    }
    
    public void setYear_issue(LocalDateTime  year_issue) {
        this.year_issue = year_issue;
    }

    public double getRaiting() {
        return this.raiting;
    }
    
    public void setRaiting(double raiting) {
        this.raiting = raiting;
    }

    public String getPath_image() {
        return this.path_image;
    }
    
    public void setPath_image(String path_image) {
        this.path_image = path_image;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("id").append("='").append(getId()).append("' ");			
      buffer.append("name").append("='").append(getName()).append("' ");			
      buffer.append("price").append("='").append(getPrice()).append("' ");			
      buffer.append("year_issue").append("='").append(getYear_issue()).append("' ");			
      buffer.append("raiting").append("='").append(getRaiting()).append("' ");			
      buffer.append("path_image").append("='").append(getPath_image()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof eProducts) ) return false;
		 eProducts castOther = ( eProducts ) other; 
         
		 return (this.getId()==castOther.getId())
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getPrice()==castOther.getPrice()) || ( this.getPrice()!=null && castOther.getPrice()!=null && this.getPrice().equals(castOther.getPrice()) ) )
 && ( (this.getYear_issue()==castOther.getYear_issue()) || ( this.getYear_issue()!=null && castOther.getYear_issue()!=null && this.getYear_issue().equals(castOther.getYear_issue()) ) )
 && (this.getRaiting()==castOther.getRaiting())
 && ( (this.getPath_image()==castOther.getPath_image()) || ( this.getPath_image()!=null && castOther.getPath_image()!=null && this.getPath_image().equals(castOther.getPath_image()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getPrice() == null ? 0 : this.getPrice().hashCode() );
         result = 37 * result + ( getYear_issue() == null ? 0 : this.getYear_issue().hashCode() );
         result = 37 * result + (int) this.getRaiting();
         result = 37 * result + ( getPath_image() == null ? 0 : this.getPath_image().hashCode() );
         return result;
   }   


}


